name: Jammand
version: '1.0-SNAPSHOT'
main: Jmmand.jammand
api-version: '1.20'
libraries:
  - io.github.duckfoo-ux:jammand-core:<version>
loader:
commands:
  Jammand:
    description: Jammand
  iv:
    description: iv